# Generated by Django 4.0.2 on 2022-06-20 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_date', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('role', models.CharField(max_length=30)),
                ('logo', models.ImageField(upload_to='media/')),
                ('summary', models.TextField()),
                ('project', models.TextField()),
                ('limitations', models.TextField()),
                ('approach', models.TextField()),
                ('benefits', models.TextField()),
                ('opportunities', models.TextField()),
                ('nobel', models.TextField()),
                ('threat', models.TextField()),
                ('financial', models.TextField()),
                ('risk', models.TextField()),
            ],
        ),
    ]
